---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-role
rules:
- apiGroups:
  - dana.io.dana.io
  resources:
  - namespacelabels
  verbs: 
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
