name: Run tests

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: exit 1
