name: test

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Test
        run: make test
