name: test

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo && go get github.com/onsi/gomega/... 
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
      - run: go version && $GOBIN/ginkgo version
      - name: test
        run: sudo make test
