name: test

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
      - name: Install ginkgo & gomega
        run: go get github.com/onsi/ginkgo/ginkgo github.com/onsi/gomega/...
      - name: Test
        run: make test
