name: test

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install ginkgo
        run: sudo apt-get update -y && sudo apt-get install -y ginkgo=2.4.0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
      - run: go version && ginkgo version
      - name: test
        run: sudo make test
