name: test

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - uses: actions/checkout@v2
      - run: go version
      - name: build
        run: sudo make build
      - name: test
        run: sudo make test
