name: test

on:  
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
      - name: install ginkgo
        run: sudo apt-get update && sudo apt-get install -y ginkgo
      - name: test
        run: make test
